 INSERT INTO roles(id,name) values (1,'ROLE_ADMIN');

INSERT INTO roles(id,name) values (2,'ROLE_CUSTOMER');

INSERT INTO roles(id,name) values (3,'ROLE_SELLER');


INSERT INTO product(id, image_url, name, price) values (1,"https://www.businessinsider.in/photo/81550050/Master.jpg","Watch1",50);
INSERT INTO product(id,image_url,name,price) values (2,'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2074932.jpg','Toy',10);

INSERT INTO product(id,image_url,name,price) values (3,'https://7man.com/wp-content/uploads/2019/10/mixed-fresh-fruit-baskets-gifts-delivery-kerala.jpg','Fruits',8);
INSERT INTO product(id,image_url,name,price) values (4,'https://www.sephora.com/productimages/sku/s2496891-main-zoom.jpg?imwidth=315','Shampoo',5);
INSERT INTO product(id,image_url,name,price) values (5,'https://media.istockphoto.com/photos/piece-of-pink-soap-3d-rendering-picture-id614724682?k=20&m=614724682&s=612x612&w=0&h=WQKIU7qnYXaXw0aOdnDLGXKXje-R6LUo1ndFnMKv2Hg=','Soap',15);
INSERT INTO product(id,image_url,name,price) values (6,'m.media-amazon.com/images/I/618F1Xwm49L._AC_SL1500_.jpg','Spoon',10);

INSERT INTO product(id,image_url,name,price) values (7,'https://cdn.shopify.com/s/files/1/0330/3299/4860/products/dwr_light_pants_pa-21su007_bg_hero_03_800x.jpg?v=1614385065','Pants',18);